package twistwordApp;


/**
* twistwordApp/twistword.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../IDL/twistwordApp.idl
* Monday, May 28, 2018 11:38:05 AM SGT
*/

public interface twistword extends twistwordOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface twistword
