# DO NOT EDIT THIS FILE!
#
# Python module mainfiles__POA generated by omniidl

import omniORB
omniORB.updateModule("mainfiles__POA")

# ** 1. Stub files contributing to this module
import mainfiles_idl

# ** 2. Sub-modules

# ** 3. End
