package twistwordApp;


/**
* twistwordApp/twistwordHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../IDL/twistwordApp.idl
* Monday, May 28, 2018 11:38:34 AM SGT
*/

abstract public class twistwordHelper
{
  private static String  _id = "IDL:twistwordApp/twistword:1.0";

  public static void insert (org.omg.CORBA.Any a, twistwordApp.twistword that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static twistwordApp.twistword extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (twistwordApp.twistwordHelper.id (), "twistword");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static twistwordApp.twistword read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_twistwordStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, twistwordApp.twistword value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static twistwordApp.twistword narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof twistwordApp.twistword)
      return (twistwordApp.twistword)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      twistwordApp._twistwordStub stub = new twistwordApp._twistwordStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static twistwordApp.twistword unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof twistwordApp.twistword)
      return (twistwordApp.twistword)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      twistwordApp._twistwordStub stub = new twistwordApp._twistwordStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
