package twistwordApp;


/**
* twistwordApp/twistwordOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../IDL/twistwordApp.idl
* Monday, May 28, 2018 11:38:34 AM SGT
*/

public interface twistwordOperations 
{
  boolean isAnswerCorrect ();
  boolean isGameOver ();
  boolean isLetterInString (char letter, String str);
  boolean isLongestWord (String str);
  String jumbleString (String str);
  String getQuestion ();
} // interface twistwordOperations
