package mainfiles;


/**
* mainfiles/Hangman.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mainfiles.idl
* Wednesday, May 9, 2018 2:42:35 PM SGT
*/

public interface Hangman extends HangmanOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman
