package mainfiles;


/**
* mainfiles/HangmanPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mainfiles.idl
* Wednesday, May 9, 2018 2:42:35 PM SGT
*/

public abstract class HangmanPOA extends org.omg.PortableServer.Servant
 implements mainfiles.HangmanOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("start", new java.lang.Integer (0));
    _methods.put ("guessedWord", new java.lang.Integer (1));
    _methods.put ("play", new java.lang.Integer (2));
    _methods.put ("inPlay", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
    _methods.put ("length", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // mainfiles/Hangman/start
       {
         String name = in.read_string ();
         boolean $result = false;
         $result = this.start (name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // mainfiles/Hangman/guessedWord
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.guessedWord (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // mainfiles/Hangman/play
       {
         String name = in.read_string ();
         char guess = in.read_char ();
         short $result = (short)0;
         $result = this.play (name, guess);
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 3:  // mainfiles/Hangman/inPlay
       {
         String name = in.read_string ();
         boolean $result = false;
         $result = this.inPlay (name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // mainfiles/Hangman/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 5:  // mainfiles/Hangman/length
       {
         String name = in.read_string ();
         short $result = (short)0;
         $result = this.length (name);
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:mainfiles/Hangman:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hangman _this() 
  {
    return HangmanHelper.narrow(
    super._this_object());
  }

  public Hangman _this(org.omg.CORBA.ORB orb) 
  {
    return HangmanHelper.narrow(
    super._this_object(orb));
  }


} // class HangmanPOA
