/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corbaclient;

import javax.swing.*;

/**
 * @author mehdi
 */
public class MainPanel extends javax.swing.JPanel {

    private LetterReceiver letterReceiver;
    private short wordLength;

    public static int count = 1;

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        this(null, (short) 5);
    }

    public MainPanel(LetterReceiver letterReceiver, short wordLength) {
        this.wordLength = wordLength;
        initComponents();
        buttonPanel.setLetterReceiver(letterReceiver);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guessPanel = new corbaclient.GuessPanel(wordLength);
        lblPic = new javax.swing.JLabel();
        buttonPanel = new corbaclient.ButtonPanel();

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(guessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 274, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                        .addComponent(guessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    public GuessPanel getGuessPanel() {
        return guessPanel;
    }

    public JLabel getLblPic() {
        return lblPic;
    }

    public ButtonPanel getButtonPanel() {
        return buttonPanel;
    }

    public void changePic() {
        ++count;
        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/%d.png", count))));
    }

    public void resetPic() {
        count = 1;
        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(String.format("/%d.png", count))));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private corbaclient.ButtonPanel buttonPanel;
    private corbaclient.GuessPanel guessPanel;
    private javax.swing.JLabel lblPic;
    // End of variables declaration//GEN-END:variables
}
