package mainfiles;


/**
* mainfiles/Hangman.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mainfiles.idl
* Friday, May 4, 2018 2:48:00 PM SGT
*/

public interface Hangman extends HangmanOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hangman
